### ISSUE TITLE
hyperapp createPortal

### ISSUE THREAD

**Issue by lifeiscontent** [infinnie/infinnie.github.io#14]
Hi @infinnie I read your post here: https://medium.com/@joanxie/use-hyperapp-enjoy-javascript-again-ab9633f7066f

I was curious if you had a solution to dealing with displaced content within hyperapp.

**Comment by infinnie** [comment]
Yes.
* Create an ordinary element and insert it into the DOM using good old jQuery or vanilla JavaScript inside a non-component ordinary function.
* Then initialize a HyperApp application within it.
* When we need to receive information within the displaced element, we could have the element trigger a custom event or jQuery event, and pass the data into that event.

**Comment by infinnie** [comment]
See also https://github.com/hyperapp/hyperapp/issues/637

**Comment by lifeiscontent** [comment]
Wow! Thank you so much! You rock @infinnie 👍
